### ISSUE TITLE
How to return multiple volumes? 

### ISSUE THREAD

**Issue by ChristianHinge** [Rigshospitalet-KFNM/DicomNode#1]
I was unable to figure out how to have the node return multiple sets of dicom images (one set for each image volume). Is there any way to achieve this?

**Comment by demiguard** [comment]
When you create the `PipelineOutput`. The first argument should a list of tuples.

A tuple should consists of a destination and a series. To return multiple dicom images, simply add more tuples to the list.

Example:
```
from dicomnode.server.output import DicomOutput

dicom_output = DicomOutput([
        (address_1, datasets_1),
        (address_2, datasets_1),
        (address_1, datasets_2),
      ])

dicom_output.send() # Should not be part of your process function
```

This code snippet send `dataset_1` to `address_1` and `address_2` and `dataset_2` to `address_1`

If you need to send using to different `PipelineOutput`s, use the `MultiOutput`
