### ISSUE TITLE
How can I debug my node?

### ISSUE THREAD

**Issue by ChristianHinge** [Rigshospitalet-KFNM/DicomNode#2]
I have written some code for a node. Is there any way that I can easily try it out by sending some locally stored dicom files and see if there are any errors?

**Comment by demiguard** [comment]
You can use DCM-tk to send dimse messages

storescu --scan-directories -nh -xs --recurse -aec $YourAETitle $localhost $port $path/to/dicoms

If an exception is raised while processing, the traceback is stored in pynetdicom logger and not the dicomnode logger. Therefore it can be helpful to enable the logger with AbstractPipeline attribute: disable_pynetdicom_logger=False

**Comment by ChristianHinge** [comment]
Sorry to comment on a closed issue, but is it possible to get a minimal example of how to send files using storescu? I have the following AbstractInput:

```
class MRInput(AbstractInput):
    def validate(self):
        return True

```

which should accept any dicom dataset if I understand correctly. However, I get "2023/04/20 20:36:48 dicomnode INFO Received dataset is not accepted by any inputs" response from the server when I sent the directory with dicom files. I also tried with the PlusOneNode (erasing requirements for tags), and the results are the same.

**Comment by ChristianHinge** [comment]
#4 I believe this PR fixes it :)
