### ISSUE TITLE
Tutorials folder is missing

### ISSUE THREAD

**Issue by ChristianHinge** [Rigshospitalet-KFNM/DicomNode#3]
The tutorials folder is missing. I was able to find the readthedocs webpage on https://dicomnode.readthedocs.io/en/latest/tutorials/tutorial_index.html, but it seems that the tutorials have not migrated there.

**Comment by demiguard** [comment]
It's a work in progress, another server related to another area of my responsibilities had some issues.
 
The tutorials can be found here for now, although they will be add to the read the docs soon (valve tm)
https://github.com/Rigshospitalet-KFNM/DicomNode/tree/main/docs/source/tutorials

**Comment by demiguard** [comment]
This have been fixed
